version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./writable:/var/www/html/writable
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ci4user
      POSTGRES_PASSWORD: ci4password
      POSTGRES_DB: ci4database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
