services:
  php:
    image: php:8.1-fpm
    container_name: ci4_php_fpm
    volumes:
      - ./Service:/var/www/html:z
    user: "${UID}:${GID}"
    networks:
      - ci4_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_URL=${APP_URL}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libicu-dev libpq-dev curl git &&  # Install git here
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        docker-php-ext-install intl pgsql &&
        php -r 'copy(\"https://getcomposer.org/installer\", \"composer-setup.php\");' &&
        php composer-setup.php &&
        php -r 'unlink(\"composer-setup.php\");' &&
        php composer.phar require firebase/php-jwt &&
        composer remove firebase/php-jwt &&
        composer require firebase/php-jwt &&
        php spark migrate &&
        php spark serve --host 0.0.0.0 --port 8080
      "
      
  db:
    image: postgres:13
    container_name: ci4_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci4_network

volumes:
  postgres_data:

networks:
  ci4_network:
    driver: bridge
