version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Service:/var/www/html
      - ./Service/writable:/var/www/html/writable   # Writable folder inside Service
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - ./Service/.env  # Ensure the .env file is loaded here
    restart: always  # Ensures that the container restarts in case of failure

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ci4user
      POSTGRES_PASSWORD: ci4password
      POSTGRES_DB: ci4database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always  # Ensures that the container restarts in case of failure

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
